### ISSUE TITLE
Raltegravir: upgrade reference to the latest project version ?

### ISSUE THREAD

**Issue by Yuri05** [Open-Systems-Pharmacology/Qualification-DDI-UGT#9]
Raltegravir: 1.1 => 1.2
Not sure if it's really required, because the latest changes in the Raltegravir snapshot do not affect DDI I think . but please check with @incei

**Comment by Incei** [comment]
No this does not affect the DDI work. we only updated the hyperlinks to be small letters

**Comment by Yuri05** [comment]
ok, not required then. closing

**Comment by sfrechen** [comment]
If we have another release of raltegravir, it sill makes sense to update to the latest release...
